services:

  mongodb:
    image: mongo:7
    container_name: blackjack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: blackjack_games

  mysql:
    image: mysql:8
    container_name: blackjack-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack_players
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: blackjack-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/blackjack_games
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack_players?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/blackjack_players?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started

volumes:
  mongo_data:
  mysql_data: