spring:
  application:
    name: blackjack

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack_games
      auto-index-creation: true

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack_players?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    pool:
      initial-size: 5
      max-size: 20

  flyway:
    url: jdbc:mysql://localhost:3306/blackjack_players?useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: root
    locations: classpath:db/migration
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    cat.itacademy.blackjack: DEBUG
    org.springframework.data.mongodb: INFO
    io.r2dbc: INFO